### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by matteofg** [gusbrs/zref-vario#1]
Hi gusbrs,
I saw that you are adding the Italian localization.
I don't know if you want to keep the exact match with the `varioref` package localizations. Otherwise, I suggest two modifications.
```
reftextfaceafter = {nella pagina \reftextvario{a~fianco}{successiva}} ,
reftextfacebefore = {nella pagina \reftextvario{a~fianco}{precedente}} ,
```
instead of
```
reftextfaceafter = {\reftextvario{a fronte}{nella pagina successiva}} ,
reftextfacebefore = {\reftextvario{a fronte}{nella pagina precedente}} ,
```
In this context the term 'fronte' is wrong.

Matteo

**Comment by gusbrs** [comment]
Hi Matteo,
indeed I have. I was improving the hyperlinks of the nearby pagerefs today and noticed that I had forgotten about it.

Well, I have taken these from `varioref` (I don't really speak Italian). They are not set in stone, but `varioref` is a very traditional package, and its defaults carry quite some weight. If you look at the comments about it, you notice that this has been around for a lot of time and has passed through several people:

```
%    Defaults for Italian suggested by Giovanni Pensa
%    (\verb=pensa@dsi.unimi.it=) with i{\TeX}nici.
% \changes{v1.1b}{1995/10/19}{Added defaults for Italian}
% \changes{v1.2a}{1998/08/22}{Removed incorrect warning}
% \changes{v1.4k}{2004/10/30}{Added missing defaults supplied by Lapo Mori}
% \changes{v1.4n}{2005/07/24}{Small change}
% \changes{v1.4u}{2009/03/21}{Correction for \cs{reftextfaraway} suggested
%                             by Lorenzo Pantieri}
```
So I need something "authoritative" not to follow it. In which case, I suggest the following. How about consulting folks at GuIT, telling them its a matter of diverging from `varioref`'s longstanding defaults, and see what people think. WDYT?

And thanks for chiming in!

**Comment by matteofg** [comment]
> I need something "authoritative" not to follow it

You are absolutely right! I will try to consult GuIT users and let you know.

See you soon,
Matteo

**Comment by matteofg** [comment]
Hi gusbrs,
since the `varioref` package has existed for so many years, I thought it is not appropriate to change the translations.
However, I don't want to use the `\zvLanguageSetup` command in EVERY `.tex` document.
Is it possible to implement a system that uses a `.cfg` file in which to enter changes to defaul localizations?
The `hyperref` package uses a similar system, where options are set in the local `hyperref.cfg` file using the `\hypersetup` command.
In this way, my `zref-vario.cfg` file would contain the following code
```
\zvLanguageSetup{italian}
	{
	reftextfaceafter = {nella~\zvhyperlink{pagina~\reftextvario{a~fianco}{successiva}}} ,
	reftextfacebefore = {nella~\zvhyperlink{pagina~\reftextvario{a~fianco}{precedente}}} ,
	}
```
Matteo

**Comment by gusbrs** [comment]
Hi Matteo,

yes, I know the config file mechanism, and indeed I had this in my todo list for `zref-clever`. I might as well just go ahead and do it for both.

However, you said that:

> In this context the term 'fronte' is wrong.

And, well, true that tradition has a lot of weight in the LaTeX community, but we shouldn't be slaves to it either. So, if it is "wrong", it should be fixed. Hence, I'd like to pursue this issue further, unless you really prefer not to.

I understand it may be too much to ask GuIT again, since you so recently asked for their advice regarding `zref-clever`. But, can you at least elaborate on why you say the current localization for `varioref` is wrong?

I get that this may be somewhat frustrating for you, after all you are a native speaker and I don't even speak the language. But please be patient and put yourself in my shoes.  ;-)

**Comment by gusbrs** [comment]
Hi Matteo,

just a heads up about the configuration file request. I've asked for some advice on the matter from the more seasoned, and I was recommended not to do it. Indeed, I was presented with good reason, namely that a config file breaks portability and  leads the same document to behave differently depending on the site it is placed, and thus potentially results in hard to trace issues.

So, I've decided to listen to the voice of experience and hence against adding support for a user config file. Sorry to disappoint on that one, but if you want to have something of the sort, a simple `\input{my-zref-vario.cfg}` is sufficient and, with it, your document makes it explicit it is doing something different from the default behavior of the package.

**Comment by matteofg** [comment]
> can you at least elaborate on why you say the current localization for `varioref` is wrong?

Perhaps I was a bit hasty to define the term 'fronte' as 'wrong'. But the translation 'a fronte' (or 'nella pagina a fronte') is a literal translation of 'facing' (or 'in the facing page) that is not currently used.
I say again: perhaps the translation is not wrong, but in Italian we normally say 'nella pagina a fianco', not 'a fronte'.
that's all ;-)

> if you want to have something of the sort, a simple \input{my-zref-vario.cfg} is sufficient and, with it, your document makes it explicit it is doing something different from the default behavior of the package.

Analyzing the pros and cons, I think that this would be the best solution.

I hope my requests and suggestions have been helpful to you regarding the development of your projects.

See you soon,
Matteo

**Comment by gusbrs** [comment]
Hi Matteo,

> Perhaps I was a bit hasty to define the term 'fronte' as 'wrong'. But the translation 'a fronte' (or 'nella pagina a fronte') is a literal translation of 'facing' (or 'in the facing page) that is not currently used.
> I say again: perhaps the translation is not wrong, but in Italian we normally say 'nella pagina a fianco', not 'a fronte'.
> that's all ;-)

I took a look on my side, and indeed the usual translating engines translate "pagina a fianco" and "pagina a fronte"  as "opposing page" and "facing page", which seem both to make sense and be appropriate to the context. Of course, granted, "literal translation", and that's your point.

Regarding use "pagina a fianco" and "pagina a fronte" seem to be somewhat equivalent:

![Screenshot from 2023-01-03 08-13-04](https://user-images.githubusercontent.com/19410606/210346607-3177abdd-cd2d-4d73-81bf-fec6523f189e.png)

(From https://books.google.com/ngrams/graph?content=pagina+a+fronte%2Cpagina+a+fianco&year_start=1940&year_end=2019&corpus=33&smoothing=3&case_insensitive=true)

(Off-topic: Curious and symptomatic decline of both in the last decades. The fall of "book" altogether...)

However, if as a native speaker of Portuguese I'm allowed to extrapolate my feeling of structure to Italian, the use of straight "a fronte" (as opposed to "nella pagina a fronte") does seem a little odd to me too.

All in all, I think I'm ready to follow your advice on this one. But, if down the road it turns out to be contentious (that is, if people complain) we re-discuss it.  What do you say?

And, confirming, your recommendation would be?:

```tex
reftextfaceafter = {nella~\zvhyperlink{pagina~\reftextvario{a~fianco}{successiva}}} ,
reftextfacebefore = {nella~\zvhyperlink{pagina~\reftextvario{a~fianco}{precedente}}} ,
```

> I hope my requests and suggestions have been helpful to you regarding the development of your projects.

Very much so! And they are much appreciated.

**Comment by matteofg** [comment]
> All in all, I think I'm ready to follow your advice on this one. But, if down the road it turns out to be contentious (that is, if people complain) we re-discuss it. What do you say?

It's fine with me 👍 

> And, confirming, your recommendation would be?:

```
reftextfaceafter = {nella~\zvhyperlink{pagina~\reftextvario{a~fianco}{successiva}}} ,
reftextfacebefore = {nella~\zvhyperlink{pagina~\reftextvario{a~fianco}{precedente}}} ,
```

Yes, I confirm the translations 👍 

Matteo

**EDIT**: thanks to your packages I don't need to use `varioref`. However, if it bothers you to have a different localization than the `varioref` package, you can corroborate my argument in front of Frank Mittelbach ;-)

**Comment by gusbrs** [comment]
> It's fine with me +1

> Yes, I confirm the translations +1

Great, thanks! Even though this is a small change, I'll prepare a release since I don't have anything else lined up at the moment, and there's no reason to keep this waiting indefinitely long either.

> thanks to your packages I don't need to use `varioref`.

I'm sorry to break it to you, but you do. `zref-vario` is just a wrapper around `varioref`, which actually does all the hard work.  ;-)
