### ISSUE TITLE
Label lists in arguments: impossible, really?

### ISSUE THREAD

**Issue by dbitouze** [gusbrs/zref-vario#2]
The documentation reads page 3:

> As such, differently from `zref-clever`’s commands, these can receive single labels as arguments, not lists of them.

But, despite a warning in the `.log` file, the label lists in the arguments seem to give the expected result. Indeed, the following MCE:
```latex
\documentclass{article}
\usepackage{zref-vario}
\begin{document}
See \zvref{foo,bar}.
\section{Foo}\label{foo}
\newpage
\section{Bar}\label{bar}
\end{document}
```
gives:

> See sections 1 and 2 on pages 1 and 2.

**Comment by gusbrs** [comment]
Well, really... and the mentioned warning tells you what's wrong: "Reference 'foo,bar' on page 1 undefined". The limitation stems from the fundamental fact that `zref-vario` is a wrapper around `varioref`, and the latter does not handle lists of labels, just a single one.

Indeed, your MCE does not render expected results. If you extend it just a little, you see what's wrong:

```tex
\documentclass{article}
\usepackage{zref-vario}
\begin{document}
See \zvref{foo,bar}.\par
See \zvref{foo}.\par
See \zvref{bar}.
\section{Foo}\label{foo}
\newpage
\section{Bar}\label{bar}
\end{document}
```
which gives:

> See sections 1 and 2 on pages 1 and 2.
> See section 1.
> See section 2 on the following page.

There is no provision to "merge" something like "on this and the following page" etc. As far as `varioref` is concerned, the undefined label just falls back into the `\zcref[page]` case (the equivalent of `\pageref` for `zref-vario`), because it does not know the page number of an undefined reference, of course. That does not mean it "is working" though...

**Comment by dbitouze** [comment]
Sorry, I don't see what's wrong with:

>See sections 1 and 2 on pages 1 and 2.
>See section 1.
>See section 2 on the following page.

**Comment by gusbrs** [comment]
> Sorry, I don't see what's wrong with:
> 
> > See sections 1 and 2 on pages 1 and 2.
> > See section 1.
> > See section 2 on the following page.

It does not use the "vario" part of `varioref`, even if these references should, because they are in the same/following page. And just because it is a list, instead of a single reference. I know `cleveref` patches `varioref` so as to support lists of labels, but I never looked into how it handles these cases, so you may have some "expected results" according to this.

Anyway, what you get there is not "working" but just a "lucky failure". If you'd like to rely on that, it is up to you. It is not recommended or supported though.

You certainly recall how this package came to be (https://github.com/gusbrs/zref-clever/issues/3), so it should be no surprise to you that this is just a wrapper around `varioref`. Thus the limitation.

**Comment by dbitouze** [comment]
Ah, now I see, sorry. 

> Thus the limitation.

Too bad! :wink:

**Comment by gusbrs** [comment]
> > Thus the limitation.
> 
> Too bad! 😉

Even if tongue in cheek, that an unfair complaint from you. :wink: 

Anyway, this is still:

> [...] a matter of "someone" doing it, of course.  (https://github.com/gusbrs/zref-clever/issues/3#issuecomment-986237139).

I'd hoped to have you (plural) satisfied but I guess it is only natural to want a little more...

**Comment by dbitouze** [comment]
> Even if tongue in cheek, that an unfair complaint from you. 😉

Sorry for that! 

> I'd hoped to have you (plural) satisfied but I guess it is only natural to want a little more...

Indeed. And sorry: I didn't test this package earlier, so (incidentally) only now make a feature request.

**Comment by gusbrs** [comment]
All good!  :smile: 

Cheers!
